name: Build and Test

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: CI on ${{ matrix.os }} - ${{ matrix.configuration }} (SDK ${{ matrix.sdk }}) 
    strategy:
      matrix:
        os: [windows-latest]
        sdk: [ 3.1.x, net46, net47 ]     
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.sdk }}
      
      - name: Build Core
        run: dotnet build  --configuration ${{ matrix.configuration }} PTI.Rs232Validator/PTI.Rs232Validator.csproj
      
      - name: Build Emulator
        run: dotnet build  --configuration ${{ matrix.configuration }} PTI.Rs232Validator.Emulator/PTI.Rs232Validator.Emulator.csproj      
      
      - name: Run Tests
        if: matrix.configuration == 'Debug'
        run: dotnet test --no-restore --verbosity normal PTI.Rs232Validator.Tests/PTI.Rs232Validator.Tests.csproj  
