name: Build and Test

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: Build check on ${{ matrix.os }} - ${{ matrix.configuration }} (SDK ${{ matrix.sdk }})
    strategy:
      matrix:
        os: [ windows-latest ]
        sdk: [ 8.0 ]
        configuration: [ Debug, Release ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.sdk }}

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} PTI.Rs232Validator/PTI.Rs232Validator.csproj
        
      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} PTI.Rs232Validator.Test/PTI.Rs232Validator.Test.csproj
