on:
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       dotnet: [ '3.1', 'net461', 'net472' ]   
   name: ${{ matrix.dotnet }} Tests
   steps:
   - uses: actions/checkout@v2
   
   - name: Setup Dotnet
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: ${{ matrix.dotnet }}
    
   - name: Install dependencies
     run: dotnet restore
     working-directory: PTI.Rs232Validator.Tests
     
   - name: Build
     run: dotnet build --configuration Release --no-restore
     working-directory: PTI.Rs232Validator.Tests
     
   - name: Run Test
     run: dotnet test --no-restore --verbosity normal
     working-directory: PTI.Rs232Validator.Tests
