name: Build and Test

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: windows-16.04
    strategy:
      matrix:
        dotnet: [ '3.1', 'net461', 'net472' ]
    name: Build and Test ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build --configuration Release
        working-directory: PTI.Rs232Validator.Tests
      - run: dotnet test
        working-directory: PTI.Rs232Validator.Tests        
